# Data
data_url: https://users.flatironinstitute.org/~polymathic/data/provabgs_desi_ls.hdf5
data_file: data/provabgs_desi_ls.hdf5

# Model
model_name: polymathic-ai/aion-base
batch_size: 32
device: cuda

# Metrics
poly_degree: 7
chi2_good_threshold: 3.0
